app_news/urls.py
from django.urls import path

from .views import (
    superuser_view,
    AddNewsView,
    ListNewsView,
    DetailNewsView,
    UpdateNewsView,
    DeleteNewsView,
    register_view,

)

urlpatterns = [
    path('add/', AddNewsView.as_view(), name='add_news'),
    path('<int:pk>/', DetailNewsView.as_view(), name='show_news'),
    path('update/<int:pk>/', UpdateNewsView.as_view(), name='update_news'),
    path('delete/<int:pk>/', DeleteNewsView.as_view(), name='delete_news'),
    path('superuser/', superuser_view, name='superuser'),
    path('register/', register_view, name='register'),
    path('', ListNewsView.as_view(), name='list_news'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/profile/', TemplateView.as_view(template_name='base.html')),
    path('accounts/register/', TemplateView.as_view(template_name='registration/register.html'), name='register'),
    path('news/', include('app_news.urls')),
    path('', TemplateView.as_view(template_name='base.html'), name='home'),
]

app_news/models.py
from django.contrib.auth import get_user_model
from django.db import models


# Create your models here.

class Category(models.Model):
    category_name = models.CharField(max_length=255)

    def __str__(self):
        return self.category_name

    class Meta:
        verbose_name_plural = "Categories"
        db_table = 'categories'


class News(models.Model):
    news_title = models.CharField(max_length=255, unique=True)
    news_description = models.CharField(max_length=255)
    news_image = models.ImageField(upload_to='news/')
    news_content = models.TextField()
    news_category = models.ForeignKey(Category, on_delete=models.CASCADE)
    news_pub_date = models.DateTimeField(auto_now_add=True)
    news_author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
        return self.news_title

    class Meta:
        verbose_name_plural = "News"
        db_table = 'news'

app_news/views.py
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.mail import send_mail
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from django.contrib.auth.models import User
from app_news.models import News
from django.http import HttpResponseRedirect, HttpResponseForbidden


def register_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
        return redirect('login')
    else:
        form = UserCreationForm()
    return render(request, 'registration/register.html', {'form': form})


class AddNewsView(LoginRequiredMixin, CreateView):
    template_name = 'news/add_news.html'
    model = News
    success_url = reverse_lazy('home')
    fields = ['news_title', 'news_description', 'news_image', 'news_content', 'news_category']

    def form_valid(self, form):
        form.instance.news_author = self.request.user
        return super().form_valid(form)


class ListNewsView(ListView):
    template_name = 'news/list_news.html'
    model = News
    paginate_by = 5


class DetailNewsView(DetailView):
    template_name = 'news/show_news.html'
    model = News


class UpdateNewsView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    template_name = 'news/update_news.html'
    model = News
    success_url = reverse_lazy('home')
    fields = ['news_title', 'news_description', 'news_image', 'news_content', 'news_category']

    def test_func(self):
        return self.request.user.is_superuser or self.get_object().news_author == self.request.user

    def handle_no_permission(self):
        return HttpResponseForbidden("Sizda yangilikni o'zgartirish uchun ruxsat yo'q.")


class DeleteNewsView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = News
    success_url = reverse_lazy('home')
    template_name = 'news/delete_news.html'

    def test_func(self):
        return self.request.user.is_superuser or self.get_object().news_author == self.request.user

    def handle_no_permission(self):
        return HttpResponseForbidden("Sizda yangilikni o'chirish uchun ruxsat yo'q.")


def superuser_view(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            # print(request.user.is_authenticated)
            try:
                all_users_emails = User.objects.values_list('email', flat=True)
                for email in all_users_emails:
                    send_mail(
                        subject=request.POST['subject'],
                        message=request.POST['message'],
                        from_email="doniyorovnurbek286@gmail.com",
                        recipient_list=[email]
                    )
                return HttpResponse("Successfully sent email to all users")
            except Exception as e:
                return HttpResponse(f"Something went wrong: {e}")
    return render(request, 'superuser.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        	Django auth
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">daily.news</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <ul class="navbar-nav">
{#        <li class="nav-item">#}
{#          <a class="nav-link" href="#">Link</a>#}
{#        </li>#}
{#        <li class="nav-item">#}
{#          <a class="nav-link" href="#">Link</a>#}
{#        </li>#}
{#        <li class="nav-item">#}
{#          <a class="nav-link" href="#">Link</a>#}
{#        </li>#}
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">News</a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'list_news' %}">All news</a></li>
                  <hr>
                <li><a class="dropdown-item" href="{% url 'add_news' %}">Add news</a></li>
              </ul>
            </li>

      </ul>
    </div>
      {% if user.is_superuser %}
          <a href="{% url 'superuser' %}" class="btn btn-secondary">superuser</a>
      {% endif %}
  </div>
            {% if user.is_authenticated %}
    	<div class="dropdown" style="text-align: right;">
          <button type="button" class="btn btn-success dropdown-toggle" data-bs-toggle="dropdown">
            {{ user.username }}
          </button>
          <ul class="dropdown-menu">
{#          <li><a class="dropdown-item" href="{% url 'mail' %}">Check mail</a></li>#}
            <li><a class="btn btn-warning" href="{% url 'password_change' %}">Password change</a></li>
            <form method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-info">logout</button>
            </form>
          </ul>
        </div>
    {% else %}
        <a href="{% url 'login' %}" class="btn btn-success">Login</a> |
        <a href="{% url 'register' %}" class="btn btn-success">Register</a> |
        <a href="{% url 'password_reset' %}" class="btn btn-danger">Forgot password</a>
    {% endif %}
</nav>

    {% block content %}

    {% endblock %}


    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/news/add_news.html
{% extends 'base.html' %}

{% block title %}
	Add news
{% endblock %}

{% block content %}
	<h1>Add news</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Insert news" class="btn btn-success">
    </form>
{% endblock %}

templates/news/delete_news.html
{% extends 'base.html' %}

{% block title %}
    Update News
{% endblock %}

{% block content %}
    <h2>Update News</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Update</button>
        <a href="{% url 'list_news' %}" class="btn btn-danger">Cancel</a>
    </form>
{% endblock %}

templates/news/list_news.html
{% extends 'base.html' %}

{% block title %}
	List news
{% endblock %}

{% block content %}
	<h1>List news</h1>
    {% for news in news_list %}
    	<p>
            <a href="{% url 'show_news' news.pk %}">{{news.id}}  ---  {{ news.news_title }}</a>
        </p>
    {% endfor %}

    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="{% url 'list_news' %}?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% endif %}

        {% for page in paginator %}
            {% if page.number == page_obj.number %}
                <li class="page-item"><a class="page-link disabled" disabled>{{ page.number }}</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="{% url 'list_news' %}?page={{ page.number }}">{{ page.number }}</a></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="{% url 'list_news' %}?page={{ page_obj.next_page_number }}">Next</a></li>
        {% endif %}
    </ul>

{% endblock %}

templates/news/show_news.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
	{{ news.news_title }}
{% endblock %}

{% block content %}
	<h1>{{ news.news_title }}</h1>
    <img src="{% static news.news_image %}" alt="" width="400" style="float:right;">
    <p>
        {{ news.news_content }}
    </p>
    <p>Author: {{ news.news_author }}</p>
    <p>Category: {{ news.news_category }}</p>
{% if user.is_authenticated %}
    <p><a href="{% url 'update_news' news.pk %}" class="btn btn-success">Update news</a></p>
    <p><a href="{% url 'delete_news' news.pk %}" class="btn btn-danger">Delete news</a></p>
{% endif %}
{% endblock %}

templates/news/update_news.html
{% extends 'base.html' %}

{% block title %}
    Update News
{% endblock %}

{% block content %}
    <h2>Update News</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Update</button>
    </form>
{% endblock %}

templates/superuser.html
{% extends 'base.html' %}

{% block title %}
	Superuser form
{% endblock %}

{% block content %}
	<form action="" method="post">
{% csrf_token %}
<fieldset>
    <legend>Send message form</legend>
    <p>
        <label for="email">Where:</label>
        <input type="email" name="email" class="form-control" id="email">
    </p>
    <p>
        <label for="subject">Subject:</label>
        <input type="text" name="subject" class="form-control" id="subject">
    </p>
    <p>
        <label for="message">text:</label>
        <textarea name="message" class="form-control"></textarea>
    </p>
    <input type="submit" value="Send message" class="form-control btn btn-success">
</fieldset>
</form>
{% endblock %}